typography_spectrum: 0.013865786138921976
color:
  brandStrength: 0.8524997953791171
  lightness: 0.4577484729234129
  saturation: 0.4384188065305352
  rhythmicContrast: 0.7579012636560947
  brandColors:
    - '#E6E2AF'
    - '#A7A37E'
    - '#EFECCA'
    - '#046380'
    - '#002F2F'
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/f7a9bc9d-09cc-4958-a3cd-2f4b01f4a81d.jpg
layout_spectrum: 0.1715513369999826
author:
  name: Anthony Gallelli
  email: anthonygallelli@gmail.com
  url: 'https://thegrid.ai/creative-core-designs/'
logo: null
name: Creative Core Designs
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/413c475c-d433-4b36-b693-d5ceda5218cb.jpg
